<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>Preview</LangVersion>

    <PackageId>Netsphere</PackageId>
    <Authors>archi-Doc</Authors>
    <Product>Netsphere</Product>
    <Description>Netsphere is a network protocol for Lp.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/archi-Doc/Netsphere</PackageProjectUrl>
    <RepositoryUrl>https://github.com/archi-Doc/Netsphere</RepositoryUrl>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Arc.Collections" Version="2.1.0" />
    <PackageReference Include="Arc.CrossChannel" Version="3.1.0" />
    <PackageReference Include="Arc.Threading" Version="0.55.0" />
    <PackageReference Include="Arc.Crypto" Version="2.1.0" />
    <PackageReference Include="Arc.Unit" Version="0.49.0" />
    <PackageReference Include="BigMachines" Version="0.600.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="SimpleCommandLine" Version="0.48.0" />
    <PackageReference Include="Tinyhand" Version="0.147.0" />
    <PackageReference Include="ValueLink" Version="0.122.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="xUnitTest" />
    <InternalsVisibleTo Include="Netsphere.CoreBenchmarks" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\NetsphereGenerator\bin\$(Configuration)\netstandard2.0\NetsphereGenerator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <AdditionalFiles Include="..\stylecop.json" Link="stylecop.json" />
  </ItemGroup>

</Project>
